### PR TITLE
remove classes from merged file

### PR DESCRIPTION
**Pull request by regineheberlein**
This file is a merger of core 0.1, measurement, and award.

URI's still need to be amended down the road.

Classes deleted are

arm:Arrangement
arm:OclcNumber
arm:SlipCase
arm:DustJacket
arm:Wrapper
arm:WrapAroundBand

### CODE REVIEW

**Comment by jak473** [comment]
Seem like the 6 classes are removed from the file. I have to admit that I've been going back and forth in my mind as to whether we should declare these terms as deprecated within the ontology. On one hand, I am alright with a complete break since this is a new version AND is being moved from one org's oversight to another; however, I also like the idea of formally declaring that something is deprecated. Does anyone have thoughts?

**Comment by regineheberlein** [comment]
I'm glad you're bringing that up. I seem to remember we had agreed to just delete the deprecated classes, but perhaps not. Personally, I think deleting and then including some language in the release notes should suffice, but that's just me.

**Comment by ruthtillman** [comment]
I am ok with a complete break because of reasons Jason mentioned but I would like to have it noted in documentation and possibly even as a comment in the file itself?

**Comment by regineheberlein** [comment]
Totally agree with the documentation. I'm less sure about the comment in the file itself--who's the audience for that (that wouldn't get the information from the documentation)?

**Comment by ruthtillman** [comment]
Perhaps it's my experience digging up random early 00s DTDs and such with no real access to documentation that makes me lead toward documentation in the code... **but** upon reflection, I realize that in that use case, deprecations don't matter. So I take it back.

**Review by ruthtillman — APPROVED** [review]
Confirmed:

- arm:Arrangement
- arm:OclcNumber
- arm:SlipCase
- arm:DustJacket
- arm:Wrapper
- arm:WrapAroundBand

removed from core file. Did not find any orphaned classes (or properties)

**Review by jak473 — APPROVED** [review]

**Pull request merged**
